### ISSUE TITLE
What are the tested versions of modules and tested os and environment?

### ISSUE THREAD

**Issue by k1moradi** [ashapsoncoe/CREST#1]
Hi, I found your newest manuscript (A connectomic study of a petascale fragment of human cerebral cortex) on bR. I tried to test your software but I get the following error.

from google.cloud import bigquery
ModuleNotFoundError: No module named 'google.cloud'

I installed google.cloud using pip in an anaconda environment under windows but it did not solve the problem. I was wondering, am I using the wrong version of the package? Anyways, I think it would be nice to document the tested module versions and how to use this tool.

**Comment by ashapsoncoe** [comment]
Hi k1moradi,

The requirements for CREST are:
Visual studio
Anaconda 3.8
pip install neuroglancer==2.13
pip install google-auth-oauthlib
pip install google-api-python-client
pip install --upgrade google-cloud-bigquery[bqstorage,pandas]
conda install -c conda-forge python-igraph

However, once working, access is currently only available to those with BigQuery access privileges. However, I will be releasing a new version which does not require this (and instead uses local SQL databases on your machine which can be downloaded) in the next couple of weeks. I will let you know when this is available. 

Thanks!

Alex

**Comment by k1moradi** [comment]
Thanks! I will test it whenever you release the local version, then.

**Comment by ashapsoncoe** [comment]
Hi k1moradi.

CREST is now available for public use, either as a standalone exe file that can be run on windows, or a standalone script that can be run on mac or windows.

See the user guide in the CREST repository for instructions on getting set up and using CREST.
