### ISSUE TITLE
pycairo wheel failed to build

### ISSUE THREAD

**Issue by neurologic** [ashapsoncoe/CREST#2]
I did finally solve this issue after trying a couple of different things (though probably not the most efficient or even 'correct' way).  
Figured I would post as an issue if anyone else came across it too (and if there are better ways to solve it).

Setting up on MacOS following README instructions.

Issue when running setup step for pycairo:  
```pip install pycairo==1.20.1```

<details>
  <summary>Error Message</summary>
  
      Collecting pycairo==1.20.1
      Using cached pycairo-1.20.1.tar.gz (344 kB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... done
      Preparing metadata (pyproject.toml) ... done
    Building wheels for collected packages: pycairo
      Building wheel for pycairo (pyproject.toml) ... error
      error: subprocess-exited-with-error
      
      × Building wheel for pycairo (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [15 lines of output]
          running bdist_wheel
          running build
          running build_py
          creating build
          creating build/lib.macosx-10.9-x86_64-cpython-38
          creating build/lib.macosx-10.9-x86_64-cpython-38/cairo
          copying cairo/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-38/cairo
          copying cairo/__init__.pyi -> build/lib.macosx-10.9-x86_64-cpython-38/cairo
          copying cairo/py.typed -> build/lib.macosx-10.9-x86_64-cpython-38/cairo
          running build_ext
          Package cairo was not found in the pkg-config search path.
          Perhaps you should add the directory containing `cairo.pc'
          to the PKG_CONFIG_PATH environment variable
          No package 'cairo' found
          Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for pycairo
    Failed to build pycairo
    ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
</details>

Solution: 
Ran ```brew install cairo```

<details>
  <summary>Full Output of ```brew install cairo```</summary>

    ==> Fetching dependencies for cairo: libpng, freetype, fontconfig, pcre2, glib, xorgproto, libxau, libxdmcp, libxcb, libx11, libxext, libxrender, lzo and pixman
    ==> Fetching libpng
    ==> Downloading https://ghcr.io/v2/homebrew/core/libpng/manifests/1.6.39
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/libpng/blobs/sha256:a19d1b6b4df35819a43ab5def000101bb902fbc85222d548
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a19d1b6b4df35819a43ab5def000101b
    ######################################################################## 100.0%
    ==> Fetching freetype
    ==> Downloading https://ghcr.io/v2/homebrew/core/freetype/manifests/2.13.0
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/freetype/blobs/sha256:4c58a078509f7dae12f54f7e6a37c187f01841147c8c8e
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:4c58a078509f7dae12f54f7e6a37c187
    ######################################################################## 100.0%
    ==> Fetching fontconfig
    ==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/manifests/2.14.2
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/blobs/sha256:5fea615f3524a847df9ea7e336a615fd4c8d9d8b2fb0
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5fea615f3524a847df9ea7e336a615fd
    ######################################################################## 100.0%
    ==> Fetching pcre2
    ==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/manifests/10.42
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/blobs/sha256:69483f445671a54f0e03f96b7ef41218913f793a84c32cf98
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:69483f445671a54f0e03f96b7ef41218
    ######################################################################## 100.0%
    ==> Fetching glib
    ==> Downloading https://ghcr.io/v2/homebrew/core/glib/manifests/2.74.5
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/glib/blobs/sha256:69a7d4a0a7351ffcc5b83023a03c254da1769823a1677905f6
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:69a7d4a0a7351ffcc5b83023a03c254d
    ######################################################################## 100.0%
    ==> Fetching xorgproto
    ==> Downloading https://ghcr.io/v2/homebrew/core/xorgproto/manifests/2022.2
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/xorgproto/blobs/sha256:d6deb2e4712bdd55eadfdcd7156814a6c42c9d94eb5cd
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:d6deb2e4712bdd55eadfdcd7156814a6
    ######################################################################## 100.0%
    ==> Fetching libxau
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxau/manifests/1.0.11
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxau/blobs/sha256:1bd9a72f005e6d7e746a95baf003b561756076623a074d7e
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:1bd9a72f005e6d7e746a95baf003b561
    ######################################################################## 100.0%
    ==> Fetching libxdmcp
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxdmcp/manifests/1.1.4
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxdmcp/blobs/sha256:3846fc5ceb4900e7bedb3ab6bcb8569f9beef52a60a6c2
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:3846fc5ceb4900e7bedb3ab6bcb8569f
    ######################################################################## 100.0%
    ==> Fetching libxcb
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxcb/manifests/1.15_1
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxcb/blobs/sha256:42b2a0a1eee03d44c137195a485153f4a185bac30f64c5ff
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:42b2a0a1eee03d44c137195a485153f4
    ######################################################################## 100.0%
    ==> Fetching libx11
    ==> Downloading https://ghcr.io/v2/homebrew/core/libx11/manifests/1.8.4
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/libx11/blobs/sha256:91e5e9c3b7becc85dd159b7998b35a727ae2317ddc69791e
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:91e5e9c3b7becc85dd159b7998b35a72
    ######################################################################## 100.0%
    ==> Fetching libxext
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxext/manifests/1.3.5
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxext/blobs/sha256:232f1d192c14de36a9cb57dfedd73943d65fdd6ce3b75e8
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:232f1d192c14de36a9cb57dfedd73943
    ######################################################################## 100.0%
    ==> Fetching libxrender
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxrender/manifests/0.9.11
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/libxrender/blobs/sha256:2ed6a16e43342c1a068a59c7f250111d88ef0f7d7e0a
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:2ed6a16e43342c1a068a59c7f250111d
    ######################################################################## 100.0%
    ==> Fetching lzo
    ==> Downloading https://ghcr.io/v2/homebrew/core/lzo/manifests/2.10
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/lzo/blobs/sha256:76d0933f626d8a1645b559b1709396a2a6fd57dbd556d2f1f18
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:76d0933f626d8a1645b559b1709396a2
    ######################################################################## 100.0%
    ==> Fetching pixman
    ==> Downloading https://ghcr.io/v2/homebrew/core/pixman/manifests/0.42.2
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/pixman/blobs/sha256:0a8a93bd44aca5367c4b4dc81241899adadd9429b6bab11e
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:0a8a93bd44aca5367c4b4dc81241899a
    ######################################################################## 100.0%
    ==> Fetching cairo
    ==> Downloading https://ghcr.io/v2/homebrew/core/cairo/manifests/1.16.0_5
    ######################################################################## 100.0%
    ==> Downloading https://ghcr.io/v2/homebrew/core/cairo/blobs/sha256:2fc4da6029167f696fc0b3c0553d36abb8e77c75f0096396d
    ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:2fc4da6029167f696fc0b3c0553d36ab
    ######################################################################## 100.0%
    ==> Installing dependencies for cairo: libpng, freetype, fontconfig, pcre2, glib, xorgproto, libxau, libxdmcp, libxcb, libx11, libxext, libxrender, lzo and pixman
    ==> Installing cairo dependency: libpng
    ==> Pouring libpng--1.6.39.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/libpng/1.6.39: 27 files, 1.3MB
    ==> Installing cairo dependency: freetype
    ==> Pouring freetype--2.13.0.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/freetype/2.13.0: 67 files, 2.4MB
    ==> Installing cairo dependency: fontconfig
    ==> Pouring fontconfig--2.14.2.arm64_big_sur.bottle.tar.gz
    ==> Regenerating font cache, this may take a while
    ==> /opt/homebrew/Cellar/fontconfig/2.14.2/bin/fc-cache -frv
    🍺  /opt/homebrew/Cellar/fontconfig/2.14.2: 88 files, 2.5MB
    ==> Installing cairo dependency: pcre2
    ==> Pouring pcre2--10.42.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/pcre2/10.42: 230 files, 6.2MB
    ==> Installing cairo dependency: glib
    ==> Pouring glib--2.74.5.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/glib/2.74.5: 449 files, 22.0MB
    ==> Installing cairo dependency: xorgproto
    ==> Pouring xorgproto--2022.2.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/xorgproto/2022.2: 268 files, 3.9MB
    ==> Installing cairo dependency: libxau
    ==> Pouring libxau--1.0.11.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/libxau/1.0.11: 21 files, 139.7KB
    ==> Installing cairo dependency: libxdmcp
    ==> Pouring libxdmcp--1.1.4.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/libxdmcp/1.1.4: 11 files, 146.6KB
    ==> Installing cairo dependency: libxcb
    ==> Pouring libxcb--1.15_1.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/libxcb/1.15_1: 2,461 files, 7.4MB
    ==> Installing cairo dependency: libx11
    ==> Pouring libx11--1.8.4.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/libx11/1.8.4: 1,054 files, 7.1MB
    ==> Installing cairo dependency: libxext
    ==> Pouring libxext--1.3.5.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/libxext/1.3.5: 87 files, 446.2KB
    ==> Installing cairo dependency: libxrender
    ==> Pouring libxrender--0.9.11.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/libxrender/0.9.11: 12 files, 214.1KB
    ==> Installing cairo dependency: lzo
    ==> Pouring lzo--2.10.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/lzo/2.10: 31 files, 580.4KB
    ==> Installing cairo dependency: pixman
    ==> Pouring pixman--0.42.2.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/pixman/0.42.2: 11 files, 843.5KB
    ==> Installing cairo
    ==> Pouring cairo--1.16.0_5.arm64_big_sur.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/cairo/1.16.0_5: 126 files, 6.4MB
    ==> Running `brew cleanup cairo`...

</details>

Re-attempt at ```pip install pycairo==1.20.1``` succeeded.

**Comment by ashapsoncoe** [comment]
Thanks I will add this to the instructions for getting set up for mac (i.e. for using via command-line) users

**Comment by neurologic** [comment]
Just a note that this might not always be necessary. I had to do it on one of my macs but not on the other (even though the environment to run CREST was set up the same on both computers after updating conda within a couple days of each other).

**Comment by ashapsoncoe** [comment]
Thanks - I added indicated this in teh setup instructions for Mac
