### ISSUE TITLE
Additional package needed

### ISSUE THREAD

**Issue by neurologic** [ashapsoncoe/CREST#3]
To complete the setup on my Mac, I needed to run:

```conda install -c conda-forge google-cloud-storage```

(until I did, ```from google.cloud import storage``` raised "*ModuleNotFoundError: No module named 'google.cloud'*"

**Comment by ashapsoncoe** [comment]
Thanks - it seems this was left out from the mac setup instructions by accident - have now added to the list of installation steps for mac
