### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by neurologic** [ashapsoncoe/CREST#4]
**OS**: Catalina 10.15.7

**CONDA ENV**: new environment created, installed pip, then installed all packages listed on the README, then installed google storage as described in the issue "additional package needed"

Launching CREST_v0.16.py worked and the GUI loaded.  
The error is triggered when I click the button to proofread a cell. The pop-up with the input box occurs correctly, but is unresponsive and all of the text and buttons in the main GUI window disappear.

<details> 
<summary>Error Message</summary>
2023-03-03 13:03:42.656 python[5630:12898027] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (              
                           
        0   AppKit                              0x00007fff2ce3b9a9 -[NSWindow(NSWindow_Theme) postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371                                                         
           
        1   AppKit                              0x00007fff2ce233d2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416  
                                                                                     
        2   AppKit                              0x00007fff2ce22e43 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42     
                                                                                         
        3   libtk8.6.dylib                      0x00000001055325cf TkMacOSXMakeRealWindowExist + 735           

        4   libtk8.6.dylib                      0x0000000105532131 TkWmMapWindow + 81                  
        
        5   libtk8.6.dylib                      0x0000000105474e2c Tk_MapWindow + 204           
               
        6   libtk8.6.dylib                      0x000000010547ebf1 MapFrame + 65                 
              
        7   libtcl8.6.dylib                     0x00000001053ac076 TclServiceIdle + 134         
               
        8   libtcl8.6.dylib                     0x000000010538a361 Tcl_DoOneEvent + 385         
               
        9   libtk8.6.dylib                      0x000000010547ebde MapFrame + 46         
                      
        10  libtcl8.6.dylib                     0x00000001053ac076 TclServiceIdle + 134           
             
        11  libtcl8.6.dylib                     0x000000010538a361 Tcl_DoOneEvent + 385             
           
        12  libtk8.6.dylib                      0x000000010544a374 Tk_UpdateObjCmd + 180                 
      
        13  libtcl8.6.dylib                     0x00000001052c9c02 Tcl_EvalObjv + 354                       
   
        14  _tkinter.cpython-310-darwin.so      0x00000001052a1fb5 Tkapp_Call + 389                
            
        15  python                              0x00000001037c8673 method_vectorcall_VARARGS + 323            
 
	16  python                              0x00000001038d63ae _PyEval_EvalFrameDefault + 35454

	17  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	18  python                              0x00000001038d63ae _PyEval_EvalFrameDefault + 35454

	19  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	20  python                              0x00000001038fe7db call_function + 187

	21  python                              0x00000001038cfd84 _PyEval_EvalFrameDefault + 9300

	22  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	23  python                              0x00000001038d9c4e _PyEval_EvalFrameDefault + 49950

	24  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	25  python                              0x00000001038de4d7 _PyEval_EvalFrameDefault + 68519

	26  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	27  python                              0x0000000103846fea slot_tp_init + 554

	28  python                              0x000000010383b74c type_call + 268

	29  python                              0x00000001038d9915 _PyEval_EvalFrameDefault + 49125

	30  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	31  python                              0x00000001038fe7db call_function + 187

	32  python                              0x00000001038cf834 _PyEval_EvalFrameDefault + 7940

	33  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	34  python                              0x00000001037bd40f method_vectorcall + 479

	35  python                              0x00000001038d83a4 _PyEval_EvalFrameDefault + 43636

	36  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	37  python                              0x00000001038d63ae _PyEval_EvalFrameDefault + 35454

	38  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	39  python                              0x00000001038d63ae _PyEval_EvalFrameDefault + 35454

	40  python                              0x00000001037b87f6 _PyFunction_Vectorcall + 582

	41  python                              0x00000001037bd40f method_vectorcall + 479

	42  python                              0x00000001039c401a thread_run + 186

	43  python                              0x0000000103964ea4 pythread_wrapper + 36

	44  libsystem_pthread.dylib             0x00007fff68e95109 _pthread_start + 148

	45  libsystem_pthread.dylib             0x00007fff68e90b8b thread_start + 15
)

2023-03-03 13:03:42.671 python[5630:12898027] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/simpledialog.py", line 188, in ok
    if not self.validate():
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/simpledialog.py", line 305, in validate
    result = self.getresult()
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/simpledialog.py", line 397, in getresult
    return self.entry.get()
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/__init__.py", line 3082, in get
    return self.tk.call(self._w, 'get')
RuntimeError: main thread is not in main loop
</details>

**Comment by ashapsoncoe** [comment]
Thanks for flagging this up, looking into it now. Haven't had this happen on windows when running from the command line, so may be mac-specific. Will get back to you as soon as there's a fix

**Comment by ashapsoncoe** [comment]
I have made some changes to the main script (download CREST_v0.19.py from the repository) which I think should help this issue.

I do not have access to a mac to test this currently, and could not reporduce the error on windows. If you find that running the new version (CREST_v0.19.py) results in the same problem, please let me know here and I'll look into it further

**Comment by neurologic** [comment]
Thanks for sharing this great tool and helping debug this!
(I can often debug things myself, but this particular error is something I am not understanding yet. I have not written any GUIs in python yet and don't understand how it integrates with the OS).  

I pulled the latest from the repo and ran it again. 

I am still getting an error:

<details>
<summary>Trace Back</summary>
2023-03-06 10:14:20.453 python[4367:14959432] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future.   

Called from (
	0   AppKit                              0x00007fff2ce3b9a9 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
	1   AppKit                              0x00007fff2ce233d2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	2   AppKit                              0x00007fff2ce22e43 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   libtk8.6.dylib                      0x00000001024d95cf TkMacOSXMakeRealWindowExist + 735
	4   libtk8.6.dylib                      0x00000001024d9131 TkWmMapWindow + 81
	5   libtk8.6.dylib                      0x000000010241be2c Tk_MapWindow + 204
	6   libtk8.6.dylib                      0x0000000102425bf1 MapFrame + 65
	7   libtcl8.6.dylib                     0x0000000102353076 TclServiceIdle + 134
	8   libtcl8.6.dylib                     0x0000000102331361 Tcl_DoOneEvent + 385
	9   libtk8.6.dylib                      0x0000000102425bde MapFrame + 46
	10  libtcl8.6.dylib                     0x0000000102353076 TclServiceIdle + 134
	11  libtcl8.6.dylib                     0x0000000102331361 Tcl_DoOneEvent + 385
	12  libtk8.6.dylib                      0x00000001023f1374 Tk_UpdateObjCmd + 180
	13  libtcl8.6.dylib                     0x0000000102270c02 Tcl_EvalObjv + 354
	14  _tkinter.cpython-310-darwin.so      0x0000000102248fb5 Tkapp_Call + 389
	15  python                              0x000000010076f673 method_vectorcall_VARARGS + 323
	16  python                              0x000000010087d3ae _PyEval_EvalFrameDefault + 35454
	17  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	18  python                              0x000000010087d3ae _PyEval_EvalFrameDefault + 35454
	19  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	20  python                              0x00000001008a57db call_function + 187
	21  python                              0x0000000100876d84 _PyEval_EvalFrameDefault + 9300
	22  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	23  python                              0x0000000100880c4e _PyEval_EvalFrameDefault + 49950
	24  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	25  python                              0x00000001008854d7 _PyEval_EvalFrameDefault + 68519
	26  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	27  python                              0x00000001007edfea slot_tp_init + 554
	28  python                              0x00000001007e274c type_call + 268
	29  python                              0x0000000100880915 _PyEval_EvalFrameDefault + 49125
	30  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	31  python                              0x00000001008a57db call_function + 187
	32  python                              0x0000000100876834 _PyEval_EvalFrameDefault + 7940
	33  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	34  python                              0x000000010076440f method_vectorcall + 479
	35  python                              0x000000010087f3a4 _PyEval_EvalFrameDefault + 43636
	36  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	37  python                              0x000000010087d3ae _PyEval_EvalFrameDefault + 35454
	38  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	39  python                              0x000000010087d3ae _PyEval_EvalFrameDefault + 35454
	40  python                              0x000000010075f7f6 _PyFunction_Vectorcall + 582
	41  python                              0x000000010076440f method_vectorcall + 479
	42  python                              0x000000010096b01a thread_run + 186
	43  python                              0x000000010090bea4 pythread_wrapper + 36
	44  libsystem_pthread.dylib             0x00007fff68e95109 _pthread_start + 148
	45  libsystem_pthread.dylib             0x00007fff68e90b8b thread_start + 15
)

2023-03-06 10:14:20.486 python[4367:14959432] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
</details>

The program runs fine on my other mac at home (setup the same way with conda). I will check what OS version that is and can add that info here if useful.   

Let me know if there are things that I can run for you on my mac to help in debugging. 
Best, Krista

**Comment by neurologic** [comment]
If it is useful...
When I try to interact with the "Enter Segment ID" popup, I get the following when pasting a cell ID and clicking "OK":

<details>
<summary> error</summary>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/simpledialog.py", line 188, in ok
    if not self.validate():
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/simpledialog.py", line 305, in validate
    result = self.getresult()
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/simpledialog.py", line 397, in getresult
    return self.entry.get()
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/__init__.py", line 3082, in get
    return self.tk.call(self._w, 'get')
RuntimeError: main thread is not in main loop
</details>

And when I click "cancel" in that popup window I get:

<details>
<summary> error</summary>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/simpledialog.py", line 204, in cancel
    self.parent.focus_set()
  File "/Users/kperks/opt/anaconda3/envs/ell-2/lib/python3.10/tkinter/__init__.py", line 765, in focus_set
    self.tk.call('focus', self._w)
RuntimeError: main thread is not in main loop
</details>

Neither button clicks cause any functionality to occur (neuroglancer tab never launches in chrome and the popup window never closes)) and the main GUI window remains blank the whole time.

**Comment by neurologic** [comment]
This issue thread seems helpful?  https://github.com/PySimpleGUI/PySimpleGUI/issues/4051

I have never used threading (or tkinter) so need to start at square1 before I have anything real to contribute to a solution.

**Comment by ashapsoncoe** [comment]
I now have access to a Mac again so will be able to try and recreate this error and start working on it

**Comment by neurologic** [comment]
Awesome! Let me know if I can provide you with any more information or tests on mine to help.

**Comment by ashapsoncoe** [comment]
Sorry for the delay on this. Unfortunately I don't have capacity to work on this at the moment, therefore CREST is not officially supported for Mac - I have added a note to the CREST instructions indicating that mac users may try to run the python script but that there may be issues with this depending on your mac setup.

Apologies, I will try to address these Mac issues when I am able
